# Generated by Django 3.1.7 on 2021-03-01 09:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0003_callbackrequests_date_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callbackrequests',
            name='date_request',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 1, 12, 8, 2, 565945), verbose_name='Время заявки'),
        ),
    ]
