# Generated by Django 3.1.7 on 2021-03-01 14:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0007_auto_20210301_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callbackrequests',
            name='date_request',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 1, 17, 35, 16, 89550), verbose_name='Время заявки'),
        ),
    ]
