# Generated by Django 3.1.7 on 2021-03-01 14:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0008_auto_20210301_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callbackrequests',
            name='date_request',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 1, 17, 49, 57, 495027), verbose_name='Время заявки'),
        ),
    ]
