# Generated by Django 3.1.7 on 2021-03-01 15:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0010_auto_20210301_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_service', models.CharField(max_length=32, verbose_name='Вид потребности')),
            ],
            options={
                'verbose_name': 'Вид потребности',
                'verbose_name_plural': 'Виды потребностей',
            },
        ),
        migrations.AlterField(
            model_name='callbackrequests',
            name='date_request',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 1, 18, 42, 0, 299289), verbose_name='Время заявки'),
        ),
        migrations.CreateModel(
            name='TypeService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_service', models.CharField(max_length=32, verbose_name='Потребность')),
                ('type_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_app.classservice', verbose_name='Вид потребности')),
            ],
            options={
                'verbose_name': 'Потребность',
                'verbose_name_plural': 'Потребности',
            },
        ),
    ]
