# Generated by Django 3.1.7 on 2021-03-01 16:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0012_auto_20210301_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callbackrequests',
            name='date_request',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 1, 19, 14, 34, 840153), verbose_name='Время заявки'),
        ),
    ]
