# Generated by Django 3.1.7 on 2021-03-01 20:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0016_auto_20210301_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callbackrequests',
            name='date_request',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 1, 23, 8, 37, 266770), verbose_name='Время заявки'),
        ),
    ]
