# Generated by Django 3.1.7 on 2021-03-01 20:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0017_auto_20210301_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callbackrequests',
            name='date_request',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 1, 23, 54, 4, 920619), verbose_name='Время заявки'),
        ),
    ]
