# Generated by Django 3.1.7 on 2021-03-02 09:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0018_auto_20210301_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callbackrequests',
            name='date_request',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 2, 12, 26, 17, 727175), verbose_name='Время заявки'),
        ),
    ]
