# Generated by Django 3.1.7 on 2021-03-02 10:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0020_auto_20210302_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callbackrequests',
            name='date_request',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 2, 13, 27, 23, 797120), verbose_name='Время заявки'),
        ),
    ]
