# Generated by Django 3.1.7 on 2021-03-15 09:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0026_auto_20210315_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callbackrequests',
            name='date_request',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 15, 12, 6, 34, 972874), verbose_name='Время заявки'),
        ),
    ]
