# Generated by Django 3.1.7 on 2021-03-15 09:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0035_auto_20210315_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callbackrequests',
            name='date_request',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 15, 12, 9, 2, 93685), verbose_name='Время заявки'),
        ),
    ]
