# Generated by Django 3.1.7 on 2021-03-15 09:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0038_auto_20210315_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callbackrequests',
            name='date_request',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 15, 12, 10, 15, 866310), verbose_name='Время заявки'),
        ),
    ]
