# Generated by Django 3.1.7 on 2021-03-01 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_auto_20210301_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientsIndividual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('second_name', models.CharField(max_length=32, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=32, verbose_name='имя')),
                ('last_name', models.CharField(max_length=32, verbose_name='Отчество')),
                ('city', models.CharField(max_length=32, verbose_name='Город')),
                ('phone', models.BigIntegerField(verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
            ],
            options={
                'verbose_name': 'Физическое лицо',
                'verbose_name_plural': 'Физические лица',
            },
        ),
        migrations.AlterModelOptions(
            name='typeuser',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='clientsentity',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.typeuser', verbose_name='Владелец'),
        ),
    ]
