# Generated by Django 3.1.7 on 2021-03-01 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_auto_20210301_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsindividual',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_app.typeuser', verbose_name='Владелец'),
            preserve_default=False,
        ),
    ]
