# Generated by Django 3.1.7 on 2021-03-01 16:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0008_auto_20210301_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsentity',
            name='date_request',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 1, 19, 11, 28, 93230), verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='clientsentity',
            name='org_bank_bic',
            field=models.BigIntegerField(verbose_name='БИК'),
        ),
        migrations.AlterField(
            model_name='clientsindividual',
            name='date_request',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 1, 19, 11, 28, 93230), verbose_name='Дата добавления'),
        ),
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_service', models.CharField(max_length=32, verbose_name='Вид потребности')),
                ('service', models.CharField(max_length=32, verbose_name='Потребность')),
                ('purchase_number', models.CharField(max_length=128, verbose_name='Номер закупки')),
                ('summ', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма')),
                ('contract_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Цена контракта')),
                ('subj_contract', models.TextField(max_length=256, verbose_name='Предмет контракта')),
                ('text_contract', models.TextField(max_length=256, verbose_name='Предназначение контракта')),
                ('prepaid_expense', models.BooleanField(verbose_name='Аванс')),
                ('indisputable_write_off', models.BooleanField(verbose_name='Бесспорное списание')),
                ('date_start', models.DateField(default='2021-03-01', verbose_name='Дата первая')),
                ('date_end', models.DateField(default='2021-03-01', verbose_name='Дата вторая')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.clientsentity', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
