# Generated by Django 3.1.7 on 2021-03-01 16:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0009_auto_20210301_1911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientsentity',
            old_name='owner',
            new_name='owner_id',
        ),
        migrations.RenameField(
            model_name='clientsindividual',
            old_name='owner',
            new_name='owner_id',
        ),
        migrations.AddField(
            model_name='applications',
            name='owner_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_app.typeuser', verbose_name='Владелец'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientsentity',
            name='date_request',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 1, 19, 14, 34, 842125), verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='clientsindividual',
            name='date_request',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 1, 19, 14, 34, 843123), verbose_name='Дата добавления'),
        ),
    ]
