# Generated by Django 3.1.7 on 2021-03-01 19:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0010_auto_20210301_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='zakon',
            field=models.CharField(default=1, max_length=16, verbose_name='Закон'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applications',
            name='indisputable_write_off',
            field=models.BooleanField(default=False, verbose_name='Бесспорное списание'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='prepaid_expense',
            field=models.BooleanField(default=False, verbose_name='Аванс'),
        ),
        migrations.AlterField(
            model_name='clientsentity',
            name='date_request',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 1, 22, 32, 34, 980619), verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='clientsindividual',
            name='date_request',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 1, 22, 32, 34, 980619), verbose_name='Дата добавления'),
        ),
    ]
