# Generated by Django 3.1.7 on 2021-03-01 20:05

import datetime
from django.db import migrations, models
import django.db.models.deletion
import user_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0012_auto_20210301_2232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название банка')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Стоимость')),
                ('bank_img', models.ImageField(upload_to=user_app.models.bankFile, verbose_name='Логотип банка')),
            ],
            options={
                'verbose_name': 'Банк',
                'verbose_name_plural': 'Банки',
            },
        ),
        migrations.AlterField(
            model_name='clientsentity',
            name='date_request',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 1, 23, 5, 25, 827242), verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='clientsindividual',
            name='date_request',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 1, 23, 5, 25, 827242), verbose_name='Дата добавления'),
        ),
        migrations.AddField(
            model_name='applications',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.banks', verbose_name='Банк'),
        ),
    ]
