# Generated by Django 3.1.7 on 2021-03-01 20:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0014_auto_20210301_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applications',
            name='bank',
        ),
        migrations.AddField(
            model_name='banks',
            name='app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.applications', verbose_name='Заявка'),
        ),
        migrations.AlterField(
            model_name='clientsentity',
            name='date_request',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 1, 23, 54, 4, 926580), verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='clientsindividual',
            name='date_request',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 1, 23, 54, 4, 926580), verbose_name='Дата добавления'),
        ),
    ]
