# Generated by Django 3.1.7 on 2021-03-02 09:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0015_auto_20210301_2354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banks',
            name='app',
        ),
        migrations.AlterField(
            model_name='applications',
            name='date_end',
            field=models.DateField(default='2021-03-02', verbose_name='Дата вторая'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='date_start',
            field=models.DateField(default='2021-03-02', verbose_name='Дата первая'),
        ),
        migrations.AlterField(
            model_name='clientsentity',
            name='date_request',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 2, 12, 26, 17, 730167), verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='clientsindividual',
            name='date_request',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 2, 12, 26, 17, 730167), verbose_name='Дата добавления'),
        ),
        migrations.CreateModel(
            name='ApplicationsBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.applications', verbose_name='Ссылка на заявку')),
                ('bank_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.banks', verbose_name='Ссылка на подходщий банк')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.typeuser', verbose_name='Ссылка на пользователя')),
            ],
            options={
                'verbose_name': 'Банк партнер',
                'verbose_name_plural': 'Банки партнеры',
            },
        ),
    ]
