# Generated by Django 3.1.7 on 2021-03-02 10:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0018_auto_20210302_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='date_request',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 2, 13, 40, 3, 135650), verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='clientsentity',
            name='date_request',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 2, 13, 40, 3, 134680), verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='clientsindividual',
            name='date_request',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 2, 13, 40, 3, 134680), verbose_name='Дата добавления'),
        ),
    ]
