# Generated by Django 3.1.7 on 2021-03-15 09:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0022_auto_20210315_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='date_request',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 15, 12, 10, 15, 869302), verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='clientsentity',
            name='date_request',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 15, 12, 10, 15, 868305), verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='clientsindividual',
            name='date_request',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 15, 12, 10, 15, 868305), verbose_name='Дата добавления'),
        ),
    ]
