# Generated by Django 3.1.7 on 2021-03-15 09:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0024_auto_20210315_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='date_request',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 15, 12, 11, 23, 643364), verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='clientsentity',
            name='date_request',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 15, 12, 11, 23, 642367), verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='clientsentity',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='clientsindividual',
            name='date_request',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 15, 12, 11, 23, 643364), verbose_name='Дата добавления'),
        ),
    ]
